[tools]
python = "latest"
node = "latest"
"pipx:poetry" = "latest"
"pipx:jupyterlab" = "latest"
"pipx:nox" = "latest"
"pipx:td-watson" = "latest"
"pipx:basedpyright" = "latest"
"npm:@mdx-js/language-server" = "latest"
ruby = "3.2"
go = "latest"
rust = "latest"
"aqua:astral-sh/ruff" = "latest"
"aqua:astral-sh/uv" = "latest"
"aqua:neovim/neovim" = "latest"
"aqua:tree-sitter/tree-sitter" = "latest"

[settings]
experimental = true
python_compile = false
idiomatic_version_file_enable_tools = ["python"]
gpg_verify = false
