[tools]
"aqua:Automattic/harper/harper-ls" = "latest"
"aqua:JohnnyMorganz/StyLua" = "latest"
"aqua:LuaLS/lua-language-server" = "latest"
"aqua:artempyanykh/marksman" = "latest"
"aqua:astral-sh/ruff" = "latest"
"aqua:astral-sh/uv" = "latest"
"aqua:biomejs/biome" = "latest"
"aqua:google/yamlfmt" = "latest"
"aqua:koalaman/shellcheck" = "latest"
"aqua:mvdan/sh" = "latest"
"aqua:neovim/neovim" = "latest"
"aqua:rust-lang/rust-analyzer" = "latest"
"aqua:tombi-toml/tombi" = "latest"
"aqua:tree-sitter/tree-sitter" = "0.25"
"cargo:selene" = "latest"
"github:skanehira/version-lsp" = "latest"
"go:github.com/mattn/efm-langserver" = "latest"
"npm:@google/gemini-cli" = "latest"
"npm:@mdx-js/language-server" = "latest"
"npm:@vtsls/language-server" = "latest"
"npm:bibtex-tidy" = "latest"
"npm:gh-actions-language-server" = "latest"
"npm:markdownlint-cli" = "latest"
"npm:prettier" = "latest"
"npm:vscode-langservers-extracted" = "latest"
"npm:yaml-language-server" = "latest"
"pipx:basedpyright" = "latest"
"pipx:jedi-language-server" = "latest"
"pipx:jupyterlab" = "latest"
"pipx:nox" = "latest"
"pipx:poetry" = "latest"
"pipx:td-watson" = "latest"
"pipx:yamllint" = "latest"
go = "latest"
node = "latest"
python = "latest"
ruby = "3.2"
rust = "latest"

[settings]
experimental = true
idiomatic_version_file_enable_tools = ["python"]
gpg_verify = false
